services:

    cfml-jupyter-kernel:
        build:
            context: .
            dockerfile: build.Dockerfile
            target: development
        volumes:
            - .:/workspace
            - ./notebook_examples:/home/jovyan/notebook_examples
        ports:
            - 8888:8888
        environment:
            - JUPYTER_TOKEN=123