services:

    jupyter:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        volumes:
            - ../cfml_kernel:/home/jovyan/kernels/cfml_kernel
            - ../cfscript_kernel:/home/jovyan/kernels/cfscript_kernel
            - ../notebooks:/home/jovyan/work
        ports:
            - 8888:8888
        environment:
            - JUPYTER_TOKEN=123