services:

    jupyter:
        build:
            context: ..
        volumes:
            - ../cfml_kernel:/home/jovyan/kernels/cfml_kernel
            - ../cfscript_kernel:/home/jovyan/kernels/cfscript_kernel
            - ..:/workspace:cached
        environment:
            - JUPYTER_TOKEN=x